# This file was generated by GoReleaser. DO NOT EDIT.
class PgFlame < Formula
  desc "A flamegraph generator for Postgres EXPLAIN ANALYZE output."
  homepage "https://github.com/mgartner/pg_flame"
  version "1.2"

  if OS.mac?
    url "https://github.com/mgartner/pg_flame/releases/download/v1.2/pg_flame_1.2_Darwin_x86_64.tar.gz"
    sha256 "7008245b5f9daa96c3da0701ea18f33c4925f9b8c7d1a0e26a308cde34ab0fda"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mgartner/pg_flame/releases/download/v1.2/pg_flame_1.2_Linux_x86_64.tar.gz"
      sha256 "959a45e9d73d8b8006a530858e290d268babfd7bcea2ba373ba392f116eebfa7"
    end
  end

  def install
    bin.install "pg_flame"
  end
end
